apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image-app
  namespace: demo-apps
  labels:
    app: bad-image-app
    scenario: image-pull-backoff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-image-app
  template:
    metadata:
      labels:
        app: bad-image-app
    spec:
      containers:
        - name: app
          image: nginx:stable
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi