apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
  namespace: demo-apps
  labels:
    app: memory-hog
    scenario: oom-killed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 256Mi  # Updated memory limit to prevent OOMKilled